name: SuikaGame Build

on:
  push:
    branches:
      - main

concurrency:
  group: prod

jobs:
  suika_build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        id: code-checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Deploy Site
        id: ssh-deploy-site
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/"
          strip_components: 1
          target: ${{ secrets.TARGET_PATH }}
          overwrite: true
          debug: true